# TUGAS 3

 ### a. Missing Value

In [50]:
import pandas as pd
import numpy as np

In [51]:
dataMV=pd.read_csv("bottle DATAFIX.csv",sep=",")
dataMV

,R_POTEMP,R_TEMP,R_Depth,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat
0,10.50,10.50,0,33.440,25.64,233.0,0.00,0,NaN,NaN
1,10.46,10.46,8,33.440,25.65,232.5,0.01,8,NaN,NaN
2,10.46,10.46,10,33.437,25.65,232.8,0.02,10,NaN,NaN
3,10.45,10.45,19,33.420,25.64,234.1,0.04,19,NaN,NaN
4,10.45,10.45,20,33.421,25.64,234.0,0.04,20,NaN,NaN
5,10.45,10.45,30,33.431,25.65,233.5,0.07,30,NaN,NaN
6,10.45,10.45,39,33.440,25.65,233.0,0.09,39,NaN,NaN
7,10.23,10.24,50,33.424,25.68,231.0,0.11,50,NaN,NaN
8,10.05,10.06,58,33.420,25.71,228.5,0.13,58,NaN,NaN
9,9.85,9.86,75,33.494,25.80,220.1,0.17,75,NaN,NaN
10,9.82,9.83,78,33.510,25.81,218.6,0.18,78,NaN,NaN
11,9.66,9.67,100,33.580,25.90,211.2,0.22,101,NaN,NaN
12,9.49,9.50,117,33.640,25.97,204.5,0.26,118,NaN,NaN
13,9.31,9.32,125,33.689,26.04,198.2,0.27,126,NaN,NaN
14,8.74,8.76,150,33.847,26.25,178.3,0.32,151,NaN,NaN
15,8.69,8.71,152,33.860,26.27,176.7,0.32,153,NaN,NaN
16,8.51,8.53,200,33.876,26.31,173.6,0.41,201,NaN,NaN
17,8.43,8.45,221,NaN,NaN,NaN,0.44,222,NaN,NaN
18,8.23,8.26,250,33.926,26.39,166.8,0.49,252,NaN,NaN
19,7.93,7.96,285,33.980,26.48,158.9,0.55,287,NaN,NaN
20,7.74,7.77,300,33.990,26.51,155.7,0.57,302,NaN,NaN
21,6.77,6.80,373,34.040,26.69,139.6,0.68,376,NaN,NaN
22,6.51,6.55,400,34.056,26.74,135.4,0.72,403,NaN,NaN
23,5.74,5.78,500,34.113,26.88,122.4,0.85,504,NaN,NaN
24,5.25,5.30,598,34.160,26.98,114.0,0.96,603,NaN,NaN
25,5.24,5.29,600,34.161,26.98,113.9,0.97,605,NaN,NaN
26,4.95,5.01,700,34.210,27.05,107.8,1.08,706,NaN,NaN
27,4.66,4.72,800,34.261,27.12,101.5,1.18,807,NaN,NaN
28,4.37,4.44,896,34.310,27.19,95.4,1.28,904,NaN,NaN
29,10.10,10.10,0,32.950,25.33,262.9,0.00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
4970,8.19,8.21,200,34.066,26.51,154.8,0.47,201,2.60,39.3
4971,7.55,7.57,250,34.086,26.62,144.9,0.54,251,1.93,28.7
4972,7.24,7.27,282,34.110,26.68,139.5,0.59,284,1.60,23.7
4973,7.06,7.09,300,34.120,26.71,136.5,0.61,302,1.45,21.4
4974,6.41,6.44,376,34.160,26.83,125.9,0.71,378,0.97,14.1
4975,6.23,6.27,400,34.178,26.87,122.6,0.74,403,0.86,12.4
4976,5.64,5.68,500,34.254,27.00,110.7,0.86,503,0.53,7.6
4977,5.31,5.36,571,34.310,27.09,103.3,0.94,575,0.41,5.8
4978,5.19,5.24,600,34.331,27.12,100.6,0.97,604,0.42,5.9
4979,4.81,4.87,700,34.394,27.21,92.5,1.06,705,0.45,6.3
4980,4.48,4.54,800,34.444,27.29,85.7,1.15,806,0.49,6.8
4981,4.29,4.36,865,34.470,27.33,82.3,1.21,872,0.51,7.0
4982,4.19,4.26,900,34.471,27.34,81.3,1.23,907,0.53,7.3
4983,3.88,3.96,1000,34.476,27.38,78.2,1.31,1008,0.57,7.8
4984,3.58,3.66,1100,34.482,27.41,75.0,1.39,1109,0.62,8.4
4985,3.28,3.37,1200,34.490,27.45,71.8,1.46,1211,0.67,9.0
4986,3.27,3.36,1202,34.490,27.45,71.7,1.47,1213,0.67,9.0
4987,14.75,14.75,0,33.510,24.87,306.4,0.00,0,5.69,98.6
4988,14.73,14.73,10,33.490,24.86,307.7,0.03,10,5.73,99.3
4989,14.61,14.61,20,33.454,24.86,308.2,0.06,20,5.80,100.2
4990,14.49,14.49,25,33.420,24.86,308.4,0.07,25,5.84,100.6
4991,14.22,14.22,30,33.429,24.92,302.4,0.09,30,5.84,100.1
4992,13.09,13.10,50,33.490,25.20,276.6,0.15,50,5.86,98.2
4993,12.65,12.66,74,33.420,25.23,274.1,0.21,74,5.74,95.2
4994,12.61,12.62,75,33.419,25.24,273.4,0.21,75,5.73,95.0
4995,11.40,11.41,99,33.440,25.49,250.6,0.28,99,5.42,87.6
4996,11.35,11.36,100,33.444,25.50,249.4,0.28,100,5.39,87.0
4997,10.15,10.16,125,33.555,25.80,221.5,0.34,126,4.59,72.2
4998,9.22,9.24,149,33.680,26.04,198.0,0.39,150,3.78,58.3
4999,9.20,9.22,150,33.682,26.05,197.6,0.39,151,3.76,58.0

In [52]:
# statistika deskriptif
dataMV.describe()

,R_POTEMP,R_TEMP,R_Depth,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat
count,4775.000000,4980.000000,5000.000000,4848.000000,4719.000000,4719.000000,4786.000000,5000.000000,2810.000000,2690.000000
mean,9.004084,8.974335,347.985200,33.828065,26.120341,192.307163,0.587048,350.541800,3.105388,50.474572
std,3.882991,3.911270,358.279702,0.495340,0.921310,84.548967,0.483150,361.426299,2.261303,38.004374
min,2.590000,2.700000,0.000000,32.520000,24.510000,60.200000,0.000000,0.000000,0.210000,3.700000
25%,5.510000,5.387500,55.000000,33.494000,25.120000,111.850000,0.150000,55.000000,0.660000,9.300000
50%,8.700000,8.610000,200.000000,33.890000,26.280000,176.100000,0.460000,201.000000,2.920000,46.150000
75%,12.180000,12.150000,600.000000,34.260000,27.000000,284.500000,0.980000,604.000000,5.450000,92.700000
max,17.100000,19.760000,1547.000000,34.700000,27.570000,341.100000,1.950000,1563.000000,6.630000,105.600000

In [53]:
# Missing Value
np.sum(dataMV.isnull())

R_POTEMP       225
R_TEMP          20
R_Depth          0
R_SALINITY     152
R_SIGMA        281
R_SVA          281
R_DYNHT        214
R_PRES           0
R_O2          2190
R_O2Sat       2310
dtype: int64

In [54]:
dataMV['R_POTEMP']=dataMV['R_POTEMP'].fillna((dataMV['R_POTEMP'].mean()))
dataMV['R_TEMP']=dataMV['R_TEMP'].fillna((dataMV['R_TEMP'].mean()))
dataMV['R_SALINITY']=dataMV['R_SALINITY'].fillna((dataMV['R_SALINITY'].mean()))
dataMV['R_SIGMA']=dataMV['R_SIGMA'].fillna((dataMV['R_SIGMA'].mean()))
dataMV['R_SVA']=dataMV['R_SVA'].fillna((dataMV['R_SVA'].mean()))
dataMV['R_DYNHT']=dataMV['R_DYNHT'].fillna((dataMV['R_DYNHT'].mean()))
dataMV['R_O2']=dataMV['R_O2'].fillna((dataMV['R_O2'].mean()))
dataMV['R_O2Sat']=dataMV['R_O2Sat'].fillna((dataMV['R_O2Sat'].mean()))
np.sum(dataMV.isnull())

R_POTEMP      0
R_TEMP        0
R_Depth       0
R_SALINITY    0
R_SIGMA       0
R_SVA         0
R_DYNHT       0
R_PRES        0
R_O2          0
R_O2Sat       0
dtype: int64

In [55]:
dataMV

,R_POTEMP,R_TEMP,R_Depth,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat
0,10.50,10.50,0,33.440000,25.640000,233.000000,0.00,0,3.105388,50.474572
1,10.46,10.46,8,33.440000,25.650000,232.500000,0.01,8,3.105388,50.474572
2,10.46,10.46,10,33.437000,25.650000,232.800000,0.02,10,3.105388,50.474572
3,10.45,10.45,19,33.420000,25.640000,234.100000,0.04,19,3.105388,50.474572
4,10.45,10.45,20,33.421000,25.640000,234.000000,0.04,20,3.105388,50.474572
5,10.45,10.45,30,33.431000,25.650000,233.500000,0.07,30,3.105388,50.474572
6,10.45,10.45,39,33.440000,25.650000,233.000000,0.09,39,3.105388,50.474572
7,10.23,10.24,50,33.424000,25.680000,231.000000,0.11,50,3.105388,50.474572
8,10.05,10.06,58,33.420000,25.710000,228.500000,0.13,58,3.105388,50.474572
9,9.85,9.86,75,33.494000,25.800000,220.100000,0.17,75,3.105388,50.474572
10,9.82,9.83,78,33.510000,25.810000,218.600000,0.18,78,3.105388,50.474572
11,9.66,9.67,100,33.580000,25.900000,211.200000,0.22,101,3.105388,50.474572
12,9.49,9.50,117,33.640000,25.970000,204.500000,0.26,118,3.105388,50.474572
13,9.31,9.32,125,33.689000,26.040000,198.200000,0.27,126,3.105388,50.474572
14,8.74,8.76,150,33.847000,26.250000,178.300000,0.32,151,3.105388,50.474572
15,8.69,8.71,152,33.860000,26.270000,176.700000,0.32,153,3.105388,50.474572
16,8.51,8.53,200,33.876000,26.310000,173.600000,0.41,201,3.105388,50.474572
17,8.43,8.45,221,33.828065,26.120341,192.307163,0.44,222,3.105388,50.474572
18,8.23,8.26,250,33.926000,26.390000,166.800000,0.49,252,3.105388,50.474572
19,7.93,7.96,285,33.980000,26.480000,158.900000,0.55,287,3.105388,50.474572
20,7.74,7.77,300,33.990000,26.510000,155.700000,0.57,302,3.105388,50.474572
21,6.77,6.80,373,34.040000,26.690000,139.600000,0.68,376,3.105388,50.474572
22,6.51,6.55,400,34.056000,26.740000,135.400000,0.72,403,3.105388,50.474572
23,5.74,5.78,500,34.113000,26.880000,122.400000,0.85,504,3.105388,50.474572
24,5.25,5.30,598,34.160000,26.980000,114.000000,0.96,603,3.105388,50.474572
25,5.24,5.29,600,34.161000,26.980000,113.900000,0.97,605,3.105388,50.474572
26,4.95,5.01,700,34.210000,27.050000,107.800000,1.08,706,3.105388,50.474572
27,4.66,4.72,800,34.261000,27.120000,101.500000,1.18,807,3.105388,50.474572
28,4.37,4.44,896,34.310000,27.190000,95.400000,1.28,904,3.105388,50.474572
29,10.10,10.10,0,32.950000,25.330000,262.900000,0.00,0,3.105388,50.474572
...,...,...,...,...,...,...,...,...,...,...
4970,8.19,8.21,200,34.066000,26.510000,154.800000,0.47,201,2.600000,39.300000
4971,7.55,7.57,250,34.086000,26.620000,144.900000,0.54,251,1.930000,28.700000
4972,7.24,7.27,282,34.110000,26.680000,139.500000,0.59,284,1.600000,23.700000
4973,7.06,7.09,300,34.120000,26.710000,136.500000,0.61,302,1.450000,21.400000
4974,6.41,6.44,376,34.160000,26.830000,125.900000,0.71,378,0.970000,14.100000
4975,6.23,6.27,400,34.178000,26.870000,122.600000,0.74,403,0.860000,12.400000
4976,5.64,5.68,500,34.254000,27.000000,110.700000,0.86,503,0.530000,7.600000
4977,5.31,5.36,571,34.310000,27.090000,103.300000,0.94,575,0.410000,5.800000
4978,5.19,5.24,600,34.331000,27.120000,100.600000,0.97,604,0.420000,5.900000
4979,4.81,4.87,700,34.394000,27.210000,92.500000,1.06,705,0.450000,6.300000
4980,4.48,4.54,800,34.444000,27.290000,85.700000,1.15,806,0.490000,6.800000
4981,4.29,4.36,865,34.470000,27.330000,82.300000,1.21,872,0.510000,7.000000
4982,4.19,4.26,900,34.471000,27.340000,81.300000,1.23,907,0.530000,7.300000
4983,3.88,3.96,1000,34.476000,27.380000,78.200000,1.31,1008,0.570000,7.800000
4984,3.58,3.66,1100,34.482000,27.410000,75.000000,1.39,1109,0.620000,8.400000
4985,3.28,3.37,1200,34.490000,27.450000,71.800000,1.46,1211,0.670000,9.000000
4986,3.27,3.36,1202,34.490000,27.450000,71.700000,1.47,1213,0.670000,9.000000
4987,14.75,14.75,0,33.510000,24.870000,306.400000,0.00,0,5.690000,98.600000
4988,14.73,14.73,10,33.490000,24.860000,307.700000,0.03,10,5.730000,99.300000
4989,14.61,14.61,20,33.454000,24.860000,308.200000,0.06,20,5.800000,100.200000
4990,14.49,14.49,25,33.420000,24.860000,308.400000,0.07,25,5.840000,100.600000
4991,14.22,14.22,30,33.429000,24.920000,302.400000,0.09,30,5.840000,100.100000
4992,13.09,13.10,50,33.490000,25.200000,276.600000,0.15,50,5.860000,98.200000
4993,12.65,12.66,74,33.420000,25.230000,274.100000,0.21,74,5.740000,95.200000
4994,12.61,12.62,75,33.419000,25.240000,273.400000,0.21,75,5.730000,95.000000
4995,11.40,11.41,99,33.440000,25.490000,250.600000,0.28,99,5.420000,87.600000
4996,11.35,11.36,100,33.444000,25.500000,249.400000,0.28,100,5.390000,87.000000
4997,10.15,10.16,125,33.555000,25.800000,221.500000,0.34,126,4.590000,72.200000
4998,9.22,9.24,149,33.680000,26.040000,198.000000,0.39,150,3.780000,58.300000
4999,9.20,9.22,150,33.682000,26.050000,197.600000,0.39,151,3.760000,58.000000

In [56]:
import csv
np.savetxt('dataout_a.csv',dataMV, delimiter=',', fmt='%f'
 ,header="R_POTEMP,R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat")

### b. Missing Value dan Outlier

In [57]:
# mengatasi outlier univariat
from scipy import stats
z=np.abs(stats.zscore(dataMV._get_numeric_data()))
print(z)
dataMV=dataMV[(z<3).all(axis=1)]
print(dataMV.shape)

[[3.94261822e-01 3.90890623e-01 9.71363997e-01 ... 9.69981599e-01
  7.86034962e-16 0.00000000e+00]
 [3.83719472e-01 3.80642220e-01 9.49032841e-01 ... 9.47844859e-01
  7.86034962e-16 0.00000000e+00]
 [3.83719472e-01 3.80642220e-01 9.43450052e-01 ... 9.42310674e-01
  7.86034962e-16 0.00000000e+00]
 ...
 [3.02016257e-01 3.03779205e-01 6.22439676e-01 ... 6.21327939e-01
  8.75917863e-01 7.79514775e-01]
 [5.69066132e-02 6.80659562e-02 5.55446207e-01 ... 5.54917718e-01
  3.98019650e-01 2.80778657e-01]
 [5.16354381e-02 6.29417551e-02 5.52654812e-01 ... 5.52150626e-01
  3.86219694e-01 2.70014568e-01]]
(4997, 10)

In [58]:
np.savetxt('dataout_b.csv',dataMV, delimiter=',', fmt='%f'
 ,header="R_POTEMP,R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat")

### c. Missing Value dan Transformasi

In [59]:
import pandas as pd
import numpy as np
data_c=pd.read_csv("dataout_a.csv",sep=",")
data_c

,# R_POTEMP,R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat
0,10.50,10.50,0.0,33.440000,25.640000,233.000000,0.00,0.0,3.105388,50.474572
1,10.46,10.46,8.0,33.440000,25.650000,232.500000,0.01,8.0,3.105388,50.474572
2,10.46,10.46,10.0,33.437000,25.650000,232.800000,0.02,10.0,3.105388,50.474572
3,10.45,10.45,19.0,33.420000,25.640000,234.100000,0.04,19.0,3.105388,50.474572
4,10.45,10.45,20.0,33.421000,25.640000,234.000000,0.04,20.0,3.105388,50.474572
5,10.45,10.45,30.0,33.431000,25.650000,233.500000,0.07,30.0,3.105388,50.474572
6,10.45,10.45,39.0,33.440000,25.650000,233.000000,0.09,39.0,3.105388,50.474572
7,10.23,10.24,50.0,33.424000,25.680000,231.000000,0.11,50.0,3.105388,50.474572
8,10.05,10.06,58.0,33.420000,25.710000,228.500000,0.13,58.0,3.105388,50.474572
9,9.85,9.86,75.0,33.494000,25.800000,220.100000,0.17,75.0,3.105388,50.474572
10,9.82,9.83,78.0,33.510000,25.810000,218.600000,0.18,78.0,3.105388,50.474572
11,9.66,9.67,100.0,33.580000,25.900000,211.200000,0.22,101.0,3.105388,50.474572
12,9.49,9.50,117.0,33.640000,25.970000,204.500000,0.26,118.0,3.105388,50.474572
13,9.31,9.32,125.0,33.689000,26.040000,198.200000,0.27,126.0,3.105388,50.474572
14,8.74,8.76,150.0,33.847000,26.250000,178.300000,0.32,151.0,3.105388,50.474572
15,8.69,8.71,152.0,33.860000,26.270000,176.700000,0.32,153.0,3.105388,50.474572
16,8.51,8.53,200.0,33.876000,26.310000,173.600000,0.41,201.0,3.105388,50.474572
17,8.43,8.45,221.0,33.828065,26.120341,192.307163,0.44,222.0,3.105388,50.474572
18,8.23,8.26,250.0,33.926000,26.390000,166.800000,0.49,252.0,3.105388,50.474572
19,7.93,7.96,285.0,33.980000,26.480000,158.900000,0.55,287.0,3.105388,50.474572
20,7.74,7.77,300.0,33.990000,26.510000,155.700000,0.57,302.0,3.105388,50.474572
21,6.77,6.80,373.0,34.040000,26.690000,139.600000,0.68,376.0,3.105388,50.474572
22,6.51,6.55,400.0,34.056000,26.740000,135.400000,0.72,403.0,3.105388,50.474572
23,5.74,5.78,500.0,34.113000,26.880000,122.400000,0.85,504.0,3.105388,50.474572
24,5.25,5.30,598.0,34.160000,26.980000,114.000000,0.96,603.0,3.105388,50.474572
25,5.24,5.29,600.0,34.161000,26.980000,113.900000,0.97,605.0,3.105388,50.474572
26,4.95,5.01,700.0,34.210000,27.050000,107.800000,1.08,706.0,3.105388,50.474572
27,4.66,4.72,800.0,34.261000,27.120000,101.500000,1.18,807.0,3.105388,50.474572
28,4.37,4.44,896.0,34.310000,27.190000,95.400000,1.28,904.0,3.105388,50.474572
29,10.10,10.10,0.0,32.950000,25.330000,262.900000,0.00,0.0,3.105388,50.474572
...,...,...,...,...,...,...,...,...,...,...
4970,8.19,8.21,200.0,34.066000,26.510000,154.800000,0.47,201.0,2.600000,39.300000
4971,7.55,7.57,250.0,34.086000,26.620000,144.900000,0.54,251.0,1.930000,28.700000
4972,7.24,7.27,282.0,34.110000,26.680000,139.500000,0.59,284.0,1.600000,23.700000
4973,7.06,7.09,300.0,34.120000,26.710000,136.500000,0.61,302.0,1.450000,21.400000
4974,6.41,6.44,376.0,34.160000,26.830000,125.900000,0.71,378.0,0.970000,14.100000
4975,6.23,6.27,400.0,34.178000,26.870000,122.600000,0.74,403.0,0.860000,12.400000
4976,5.64,5.68,500.0,34.254000,27.000000,110.700000,0.86,503.0,0.530000,7.600000
4977,5.31,5.36,571.0,34.310000,27.090000,103.300000,0.94,575.0,0.410000,5.800000
4978,5.19,5.24,600.0,34.331000,27.120000,100.600000,0.97,604.0,0.420000,5.900000
4979,4.81,4.87,700.0,34.394000,27.210000,92.500000,1.06,705.0,0.450000,6.300000
4980,4.48,4.54,800.0,34.444000,27.290000,85.700000,1.15,806.0,0.490000,6.800000
4981,4.29,4.36,865.0,34.470000,27.330000,82.300000,1.21,872.0,0.510000,7.000000
4982,4.19,4.26,900.0,34.471000,27.340000,81.300000,1.23,907.0,0.530000,7.300000
4983,3.88,3.96,1000.0,34.476000,27.380000,78.200000,1.31,1008.0,0.570000,7.800000
4984,3.58,3.66,1100.0,34.482000,27.410000,75.000000,1.39,1109.0,0.620000,8.400000
4985,3.28,3.37,1200.0,34.490000,27.450000,71.800000,1.46,1211.0,0.670000,9.000000
4986,3.27,3.36,1202.0,34.490000,27.450000,71.700000,1.47,1213.0,0.670000,9.000000
4987,14.75,14.75,0.0,33.510000,24.870000,306.400000,0.00,0.0,5.690000,98.600000
4988,14.73,14.73,10.0,33.490000,24.860000,307.700000,0.03,10.0,5.730000,99.300000
4989,14.61,14.61,20.0,33.454000,24.860000,308.200000,0.06,20.0,5.800000,100.200000
4990,14.49,14.49,25.0,33.420000,24.860000,308.400000,0.07,25.0,5.840000,100.600000
4991,14.22,14.22,30.0,33.429000,24.920000,302.400000,0.09,30.0,5.840000,100.100000
4992,13.09,13.10,50.0,33.490000,25.200000,276.600000,0.15,50.0,5.860000,98.200000
4993,12.65,12.66,74.0,33.420000,25.230000,274.100000,0.21,74.0,5.740000,95.200000
4994,12.61,12.62,75.0,33.419000,25.240000,273.400000,0.21,75.0,5.730000,95.000000
4995,11.40,11.41,99.0,33.440000,25.490000,250.600000,0.28,99.0,5.420000,87.600000
4996,11.35,11.36,100.0,33.444000,25.500000,249.400000,0.28,100.0,5.390000,87.000000
4997,10.15,10.16,125.0,33.555000,25.800000,221.500000,0.34,126.0,4.590000,72.200000
4998,9.22,9.24,149.0,33.680000,26.040000,198.000000,0.39,150.0,3.780000,58.300000
4999,9.20,9.22,150.0,33.682000,26.050000,197.600000,0.39,151.0,3.760000,58.000000

In [60]:
x=data_c.iloc[0:5000,1:10] #iloc buat ambil data ke-
x.tail()

,R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat
4995,11.41,99.0,33.440,25.49,250.6,0.28,99.0,5.42,87.6
4996,11.36,100.0,33.444,25.50,249.4,0.28,100.0,5.39,87.0
4997,10.16,125.0,33.555,25.80,221.5,0.34,126.0,4.59,72.2
4998,9.24,149.0,33.680,26.04,198.0,0.39,150.0,3.78,58.3
4999,9.22,150.0,33.682,26.05,197.6,0.39,151.0,3.76,58.0

In [61]:
from sklearn.preprocessing import normalize
xnorm=normalize(x,norm='l2') #default norm l2, other are l1 and max
xnorm=pd.DataFrame(xnorm)
xnorm.tail()

,0,1,2,3,4,5,6,7,8
4995,0.037617,0.326387,0.110246,0.084036,0.826187,0.000923,0.326387,0.017869,0.288803
4996,0.037515,0.330236,0.110444,0.084210,0.823608,0.000925,0.330236,0.017800,0.287305
4997,0.034309,0.422114,0.113312,0.087124,0.747986,0.001148,0.425491,0.015500,0.243813
4998,0.030935,0.498844,0.112759,0.087180,0.662893,0.001306,0.502192,0.012655,0.195185
4999,0.030798,0.501050,0.112509,0.087016,0.660050,0.001303,0.504390,0.012560,0.193739

In [62]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)
xsoft=softmax(xnorm)
xsoft=pd.DataFrame(xsoft)
print(xsoft)

             0         1         2         3         4       5         6  \
0     0.000204  0.000123  0.000212  0.000209  0.000290  0.0002  0.000123
1     0.000204  0.000127  0.000212  0.000209  0.000290  0.0002  0.000127
2     0.000204  0.000128  0.000212  0.000209  0.000290  0.0002  0.000128
3     0.000204  0.000133  0.000212  0.000209  0.000289  0.0002  0.000132
4     0.000204  0.000133  0.000212  0.000209  0.000288  0.0002  0.000133
5     0.000204  0.000139  0.000211  0.000209  0.000286  0.0002  0.000138
6     0.000203  0.000144  0.000211  0.000209  0.000283  0.0002  0.000143
7     0.000203  0.000150  0.000211  0.000208  0.000279  0.0002  0.000150
8     0.000203  0.000155  0.000211  0.000208  0.000275  0.0002  0.000154
9     0.000203  0.000165  0.000211  0.000208  0.000265  0.0002  0.000165
10    0.000203  0.000167  0.000211  0.000208  0.000263  0.0002  0.000167
11    0.000202  0.000180  0.000210  0.000208  0.000248  0.0002  0.000180
12    0.000202  0.000189  0.000209  0.000207  0.000235  0.0002  0.000189
13    0.000202  0.000194  0.000209  0.000207  0.000229  0.0002  0.000194
14    0.000201  0.000208  0.000208  0.000206  0.000207  0.0002  0.000208
15    0.000201  0.000209  0.000208  0.000206  0.000206  0.0002  0.000209
16    0.000200  0.000222  0.000204  0.000203  0.000185  0.0002  0.000222
17    0.000200  0.000222  0.000202  0.000202  0.000186  0.0002  0.000222
18    0.000199  0.000230  0.000201  0.000201  0.000169  0.0002  0.000231
19    0.000199  0.000235  0.000199  0.000200  0.000159  0.0002  0.000235
20    0.000198  0.000237  0.000199  0.000199  0.000156  0.0002  0.000237
21    0.000198  0.000242  0.000196  0.000197  0.000143  0.0002  0.000242
22    0.000197  0.000243  0.000196  0.000197  0.000140  0.0002  0.000243
23    0.000197  0.000245  0.000193  0.000195  0.000131  0.0002  0.000246
24    0.000196  0.000247  0.000192  0.000194  0.000127  0.0002  0.000247
25    0.000196  0.000247  0.000192  0.000194  0.000127  0.0002  0.000247
26    0.000196  0.000247  0.000191  0.000193  0.000124  0.0002  0.000248
27    0.000196  0.000248  0.000190  0.000193  0.000121  0.0002  0.000248
28    0.000196  0.000248  0.000190  0.000192  0.000120  0.0002  0.000249
29    0.000203  0.000123  0.000208  0.000207  0.000293  0.0002  0.000123
...        ...       ...       ...       ...       ...     ...       ...
4970  0.000200  0.000226  0.000205  0.000204  0.000178  0.0002  0.000226
4971  0.000199  0.000235  0.000202  0.000202  0.000161  0.0002  0.000235
4972  0.000198  0.000238  0.000200  0.000200  0.000154  0.0002  0.000238
4973  0.000198  0.000240  0.000199  0.000200  0.000150  0.0002  0.000240
4974  0.000197  0.000244  0.000196  0.000198  0.000140  0.0002  0.000244
4975  0.000197  0.000244  0.000196  0.000197  0.000137  0.0002  0.000245
4976  0.000197  0.000246  0.000194  0.000195  0.000129  0.0002  0.000247
4977  0.000196  0.000247  0.000192  0.000194  0.000126  0.0002  0.000247
4978  0.000196  0.000247  0.000192  0.000194  0.000125  0.0002  0.000248
4979  0.000196  0.000248  0.000191  0.000193  0.000122  0.0002  0.000248
4980  0.000196  0.000248  0.000190  0.000193  0.000120  0.0002  0.000249
4981  0.000196  0.000248  0.000190  0.000192  0.000119  0.0002  0.000249
4982  0.000196  0.000248  0.000190  0.000192  0.000118  0.0002  0.000249
4983  0.000196  0.000248  0.000189  0.000192  0.000117  0.0002  0.000249
4984  0.000196  0.000248  0.000189  0.000191  0.000116  0.0002  0.000249
4985  0.000195  0.000248  0.000188  0.000191  0.000116  0.0002  0.000249
4986  0.000195  0.000248  0.000188  0.000191  0.000116  0.0002  0.000249
4987  0.000204  0.000123  0.000205  0.000203  0.000285  0.0002  0.000123
4988  0.000204  0.000127  0.000205  0.000203  0.000285  0.0002  0.000126
4989  0.000204  0.000131  0.000204  0.000203  0.000284  0.0002  0.000130
4990  0.000204  0.000133  0.000204  0.000203  0.000283  0.0002  0.000132
4991  0.000204  0.000135  0.000205  0.000203  0.000282  0.0002  0.000134
4992  0.000204  0.000145  0.000206  0.000204  0.000275  0.0002  0.000144
4993  0.000203  0.000156  0.000205  0.000204  0.000267  0.0002  0.000155
4994  0.000203  0.000156  0.000205  0.000204  0.000267  0.0002  0.000156
4995  0.000203  0.000170  0.000206  0.000205  0.000254  0.0002  0.000170
4996  0.000203  0.000171  0.000206  0.000205  0.000253  0.0002  0.000170
4997  0.000202  0.000188  0.000207  0.000205  0.000234  0.0002  0.000188
4998  0.000201  0.000202  0.000207  0.000205  0.000215  0.0002  0.000202
4999  0.000201  0.000203  0.000207  0.000205  0.000215  0.0002  0.000203

             7         8
0     0.000201  0.000213
1     0.000201  0.000213
2     0.000201  0.000213
3     0.000201  0.000213
4     0.000201  0.000213
5     0.000201  0.000213
6     0.000201  0.000212
7     0.000201  0.000212
8     0.000201  0.000212
9     0.000201  0.000212
10    0.000201  0.000211
11    0.000201  0.000210
12    0.000201  0.000209
13    0.000201  0.000208
14    0.000200  0.000207
15    0.000200  0.000207
16    0.000200  0.000201
17    0.000200  0.000198
18    0.000200  0.000197
19    0.000200  0.000194
20    0.000200  0.000193
21    0.000199  0.000190
22    0.000199  0.000189
23    0.000199  0.000186
24    0.000199  0.000184
25    0.000199  0.000184
26    0.000199  0.000182
27    0.000199  0.000181
28    0.000199  0.000180
29    0.000201  0.000209
...        ...       ...
4970  0.000200  0.000195
4971  0.000199  0.000187
4972  0.000199  0.000183
4973  0.000199  0.000182
4974  0.000199  0.000178
4975  0.000199  0.000177
4976  0.000198  0.000175
4977  0.000198  0.000175
4978  0.000198  0.000174
4979  0.000198  0.000174
4980  0.000198  0.000174
4981  0.000198  0.000174
4982  0.000198  0.000174
4983  0.000198  0.000174
4984  0.000198  0.000174
4985  0.000198  0.000174
4986  0.000198  0.000174
4987  0.000202  0.000235
4988  0.000202  0.000235
4989  0.000202  0.000235
4990  0.000202  0.000235
4991  0.000202  0.000236
4992  0.000202  0.000239
4993  0.000202  0.000235
4994  0.000202  0.000235
4995  0.000202  0.000231
4996  0.000202  0.000231
4997  0.000201  0.000221
4998  0.000201  0.000211
4999  0.000201  0.000210

[5000 rows x 9 columns]

In [63]:
np.savetxt('datatrans1.csv',xsoft, delimiter=',', fmt='%f'
 ,header="R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat")

### d. Missing Value, Outlier, dan Transformasi

In [64]:
import pandas as pd
import numpy as np
data_d=pd.read_csv("dataout_b.csv",sep=",")
data_d

,# R_POTEMP,R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat
0,10.50,10.50,0.0,33.440000,25.640000,233.000000,0.00,0.0,3.105388,50.474572
1,10.46,10.46,8.0,33.440000,25.650000,232.500000,0.01,8.0,3.105388,50.474572
2,10.46,10.46,10.0,33.437000,25.650000,232.800000,0.02,10.0,3.105388,50.474572
3,10.45,10.45,19.0,33.420000,25.640000,234.100000,0.04,19.0,3.105388,50.474572
4,10.45,10.45,20.0,33.421000,25.640000,234.000000,0.04,20.0,3.105388,50.474572
5,10.45,10.45,30.0,33.431000,25.650000,233.500000,0.07,30.0,3.105388,50.474572
6,10.45,10.45,39.0,33.440000,25.650000,233.000000,0.09,39.0,3.105388,50.474572
7,10.23,10.24,50.0,33.424000,25.680000,231.000000,0.11,50.0,3.105388,50.474572
8,10.05,10.06,58.0,33.420000,25.710000,228.500000,0.13,58.0,3.105388,50.474572
9,9.85,9.86,75.0,33.494000,25.800000,220.100000,0.17,75.0,3.105388,50.474572
10,9.82,9.83,78.0,33.510000,25.810000,218.600000,0.18,78.0,3.105388,50.474572
11,9.66,9.67,100.0,33.580000,25.900000,211.200000,0.22,101.0,3.105388,50.474572
12,9.49,9.50,117.0,33.640000,25.970000,204.500000,0.26,118.0,3.105388,50.474572
13,9.31,9.32,125.0,33.689000,26.040000,198.200000,0.27,126.0,3.105388,50.474572
14,8.74,8.76,150.0,33.847000,26.250000,178.300000,0.32,151.0,3.105388,50.474572
15,8.69,8.71,152.0,33.860000,26.270000,176.700000,0.32,153.0,3.105388,50.474572
16,8.51,8.53,200.0,33.876000,26.310000,173.600000,0.41,201.0,3.105388,50.474572
17,8.43,8.45,221.0,33.828065,26.120341,192.307163,0.44,222.0,3.105388,50.474572
18,8.23,8.26,250.0,33.926000,26.390000,166.800000,0.49,252.0,3.105388,50.474572
19,7.93,7.96,285.0,33.980000,26.480000,158.900000,0.55,287.0,3.105388,50.474572
20,7.74,7.77,300.0,33.990000,26.510000,155.700000,0.57,302.0,3.105388,50.474572
21,6.77,6.80,373.0,34.040000,26.690000,139.600000,0.68,376.0,3.105388,50.474572
22,6.51,6.55,400.0,34.056000,26.740000,135.400000,0.72,403.0,3.105388,50.474572
23,5.74,5.78,500.0,34.113000,26.880000,122.400000,0.85,504.0,3.105388,50.474572
24,5.25,5.30,598.0,34.160000,26.980000,114.000000,0.96,603.0,3.105388,50.474572
25,5.24,5.29,600.0,34.161000,26.980000,113.900000,0.97,605.0,3.105388,50.474572
26,4.95,5.01,700.0,34.210000,27.050000,107.800000,1.08,706.0,3.105388,50.474572
27,4.66,4.72,800.0,34.261000,27.120000,101.500000,1.18,807.0,3.105388,50.474572
28,4.37,4.44,896.0,34.310000,27.190000,95.400000,1.28,904.0,3.105388,50.474572
29,10.10,10.10,0.0,32.950000,25.330000,262.900000,0.00,0.0,3.105388,50.474572
...,...,...,...,...,...,...,...,...,...,...
4967,8.19,8.21,200.0,34.066000,26.510000,154.800000,0.47,201.0,2.600000,39.300000
4968,7.55,7.57,250.0,34.086000,26.620000,144.900000,0.54,251.0,1.930000,28.700000
4969,7.24,7.27,282.0,34.110000,26.680000,139.500000,0.59,284.0,1.600000,23.700000
4970,7.06,7.09,300.0,34.120000,26.710000,136.500000,0.61,302.0,1.450000,21.400000
4971,6.41,6.44,376.0,34.160000,26.830000,125.900000,0.71,378.0,0.970000,14.100000
4972,6.23,6.27,400.0,34.178000,26.870000,122.600000,0.74,403.0,0.860000,12.400000
4973,5.64,5.68,500.0,34.254000,27.000000,110.700000,0.86,503.0,0.530000,7.600000
4974,5.31,5.36,571.0,34.310000,27.090000,103.300000,0.94,575.0,0.410000,5.800000
4975,5.19,5.24,600.0,34.331000,27.120000,100.600000,0.97,604.0,0.420000,5.900000
4976,4.81,4.87,700.0,34.394000,27.210000,92.500000,1.06,705.0,0.450000,6.300000
4977,4.48,4.54,800.0,34.444000,27.290000,85.700000,1.15,806.0,0.490000,6.800000
4978,4.29,4.36,865.0,34.470000,27.330000,82.300000,1.21,872.0,0.510000,7.000000
4979,4.19,4.26,900.0,34.471000,27.340000,81.300000,1.23,907.0,0.530000,7.300000
4980,3.88,3.96,1000.0,34.476000,27.380000,78.200000,1.31,1008.0,0.570000,7.800000
4981,3.58,3.66,1100.0,34.482000,27.410000,75.000000,1.39,1109.0,0.620000,8.400000
4982,3.28,3.37,1200.0,34.490000,27.450000,71.800000,1.46,1211.0,0.670000,9.000000
4983,3.27,3.36,1202.0,34.490000,27.450000,71.700000,1.47,1213.0,0.670000,9.000000
4984,14.75,14.75,0.0,33.510000,24.870000,306.400000,0.00,0.0,5.690000,98.600000
4985,14.73,14.73,10.0,33.490000,24.860000,307.700000,0.03,10.0,5.730000,99.300000
4986,14.61,14.61,20.0,33.454000,24.860000,308.200000,0.06,20.0,5.800000,100.200000
4987,14.49,14.49,25.0,33.420000,24.860000,308.400000,0.07,25.0,5.840000,100.600000
4988,14.22,14.22,30.0,33.429000,24.920000,302.400000,0.09,30.0,5.840000,100.100000
4989,13.09,13.10,50.0,33.490000,25.200000,276.600000,0.15,50.0,5.860000,98.200000
4990,12.65,12.66,74.0,33.420000,25.230000,274.100000,0.21,74.0,5.740000,95.200000
4991,12.61,12.62,75.0,33.419000,25.240000,273.400000,0.21,75.0,5.730000,95.000000
4992,11.40,11.41,99.0,33.440000,25.490000,250.600000,0.28,99.0,5.420000,87.600000
4993,11.35,11.36,100.0,33.444000,25.500000,249.400000,0.28,100.0,5.390000,87.000000
4994,10.15,10.16,125.0,33.555000,25.800000,221.500000,0.34,126.0,4.590000,72.200000
4995,9.22,9.24,149.0,33.680000,26.040000,198.000000,0.39,150.0,3.780000,58.300000
4996,9.20,9.22,150.0,33.682000,26.050000,197.600000,0.39,151.0,3.760000,58.000000

In [65]:
x=data_d.iloc[0:4997,1:10] #iloc buat ambil data ke-
x.tail()

,R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat
4992,11.41,99.0,33.440,25.49,250.6,0.28,99.0,5.42,87.6
4993,11.36,100.0,33.444,25.50,249.4,0.28,100.0,5.39,87.0
4994,10.16,125.0,33.555,25.80,221.5,0.34,126.0,4.59,72.2
4995,9.24,149.0,33.680,26.04,198.0,0.39,150.0,3.78,58.3
4996,9.22,150.0,33.682,26.05,197.6,0.39,151.0,3.76,58.0

In [66]:
from sklearn.preprocessing import normalize
xnorm=normalize(x,norm='l2') #default norm l2, other are l1 and max
xnorm=pd.DataFrame(xnorm)
xnorm.tail()

,0,1,2,3,4,5,6,7,8
4992,0.037617,0.326387,0.110246,0.084036,0.826187,0.000923,0.326387,0.017869,0.288803
4993,0.037515,0.330236,0.110444,0.084210,0.823608,0.000925,0.330236,0.017800,0.287305
4994,0.034309,0.422114,0.113312,0.087124,0.747986,0.001148,0.425491,0.015500,0.243813
4995,0.030935,0.498844,0.112759,0.087180,0.662893,0.001306,0.502192,0.012655,0.195185
4996,0.030798,0.501050,0.112509,0.087016,0.660050,0.001303,0.504390,0.012560,0.193739

In [67]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)
xsoft=softmax(xnorm)
xsoft=pd.DataFrame(xsoft)
print(xsoft)

             0         1         2         3         4       5         6  \
0     0.000204  0.000123  0.000212  0.000209  0.000290  0.0002  0.000123
1     0.000204  0.000127  0.000212  0.000209  0.000290  0.0002  0.000127
2     0.000204  0.000128  0.000212  0.000209  0.000290  0.0002  0.000128
3     0.000204  0.000133  0.000212  0.000209  0.000289  0.0002  0.000133
4     0.000204  0.000134  0.000212  0.000209  0.000289  0.0002  0.000133
5     0.000204  0.000139  0.000212  0.000209  0.000286  0.0002  0.000138
6     0.000204  0.000144  0.000211  0.000209  0.000283  0.0002  0.000143
7     0.000203  0.000150  0.000211  0.000209  0.000279  0.0002  0.000150
8     0.000203  0.000155  0.000211  0.000208  0.000275  0.0002  0.000154
9     0.000203  0.000165  0.000211  0.000208  0.000265  0.0002  0.000165
10    0.000203  0.000167  0.000211  0.000208  0.000263  0.0002  0.000167
11    0.000203  0.000180  0.000210  0.000208  0.000248  0.0002  0.000180
12    0.000202  0.000189  0.000209  0.000207  0.000236  0.0002  0.000189
13    0.000202  0.000194  0.000209  0.000207  0.000229  0.0002  0.000194
14    0.000201  0.000208  0.000208  0.000206  0.000207  0.0002  0.000208
15    0.000201  0.000209  0.000208  0.000206  0.000206  0.0002  0.000209
16    0.000200  0.000222  0.000204  0.000203  0.000185  0.0002  0.000222
17    0.000200  0.000222  0.000202  0.000202  0.000186  0.0002  0.000222
18    0.000199  0.000231  0.000201  0.000201  0.000169  0.0002  0.000231
19    0.000199  0.000235  0.000200  0.000200  0.000159  0.0002  0.000236
20    0.000199  0.000237  0.000199  0.000199  0.000156  0.0002  0.000237
21    0.000198  0.000242  0.000196  0.000198  0.000143  0.0002  0.000242
22    0.000197  0.000243  0.000196  0.000197  0.000140  0.0002  0.000243
23    0.000197  0.000246  0.000194  0.000195  0.000131  0.0002  0.000246
24    0.000196  0.000247  0.000192  0.000194  0.000127  0.0002  0.000247
25    0.000196  0.000247  0.000192  0.000194  0.000127  0.0002  0.000247
26    0.000196  0.000247  0.000191  0.000193  0.000124  0.0002  0.000248
27    0.000196  0.000248  0.000190  0.000193  0.000121  0.0002  0.000248
28    0.000196  0.000248  0.000190  0.000192  0.000120  0.0002  0.000249
29    0.000203  0.000123  0.000209  0.000207  0.000293  0.0002  0.000123
...        ...       ...       ...       ...       ...     ...       ...
4967  0.000200  0.000226  0.000205  0.000204  0.000178  0.0002  0.000226
4968  0.000199  0.000235  0.000202  0.000202  0.000162  0.0002  0.000235
4969  0.000199  0.000238  0.000200  0.000200  0.000154  0.0002  0.000239
4970  0.000198  0.000240  0.000199  0.000200  0.000150  0.0002  0.000240
4971  0.000198  0.000244  0.000197  0.000198  0.000140  0.0002  0.000244
4972  0.000197  0.000244  0.000196  0.000197  0.000137  0.0002  0.000245
4973  0.000197  0.000247  0.000194  0.000195  0.000129  0.0002  0.000247
4974  0.000196  0.000247  0.000193  0.000195  0.000126  0.0002  0.000248
4975  0.000196  0.000248  0.000192  0.000194  0.000125  0.0002  0.000248
4976  0.000196  0.000248  0.000191  0.000193  0.000122  0.0002  0.000248
4977  0.000196  0.000248  0.000190  0.000193  0.000120  0.0002  0.000249
4978  0.000196  0.000248  0.000190  0.000192  0.000119  0.0002  0.000249
4979  0.000196  0.000248  0.000190  0.000192  0.000118  0.0002  0.000249
4980  0.000196  0.000248  0.000189  0.000192  0.000117  0.0002  0.000249
4981  0.000196  0.000249  0.000189  0.000192  0.000116  0.0002  0.000249
4982  0.000196  0.000249  0.000188  0.000191  0.000116  0.0002  0.000249
4983  0.000196  0.000249  0.000188  0.000191  0.000116  0.0002  0.000249
4984  0.000204  0.000123  0.000205  0.000203  0.000285  0.0002  0.000123
4985  0.000204  0.000127  0.000205  0.000203  0.000285  0.0002  0.000126
4986  0.000204  0.000131  0.000204  0.000203  0.000284  0.0002  0.000130
4987  0.000204  0.000133  0.000204  0.000203  0.000283  0.0002  0.000132
4988  0.000204  0.000135  0.000205  0.000203  0.000282  0.0002  0.000134
4989  0.000204  0.000145  0.000206  0.000204  0.000275  0.0002  0.000144
4990  0.000203  0.000156  0.000206  0.000204  0.000268  0.0002  0.000155
4991  0.000203  0.000157  0.000206  0.000204  0.000267  0.0002  0.000156
4992  0.000203  0.000171  0.000206  0.000205  0.000254  0.0002  0.000170
4993  0.000203  0.000171  0.000206  0.000205  0.000253  0.0002  0.000171
4994  0.000202  0.000188  0.000207  0.000205  0.000235  0.0002  0.000188
4995  0.000201  0.000203  0.000207  0.000205  0.000215  0.0002  0.000203
4996  0.000201  0.000203  0.000207  0.000205  0.000215  0.0002  0.000203

             7         8
0     0.000201  0.000214
1     0.000201  0.000214
2     0.000201  0.000213
3     0.000201  0.000213
4     0.000201  0.000213
5     0.000201  0.000213
6     0.000201  0.000212
7     0.000201  0.000212
8     0.000201  0.000212
9     0.000201  0.000212
10    0.000201  0.000212
11    0.000201  0.000210
12    0.000201  0.000209
13    0.000201  0.000208
14    0.000201  0.000207
15    0.000201  0.000207
16    0.000200  0.000201
17    0.000200  0.000198
18    0.000200  0.000197
19    0.000200  0.000194
20    0.000200  0.000194
21    0.000200  0.000190
22    0.000199  0.000189
23    0.000199  0.000186
24    0.000199  0.000184
25    0.000199  0.000184
26    0.000199  0.000182
27    0.000199  0.000181
28    0.000199  0.000180
29    0.000201  0.000209
...        ...       ...
4967  0.000200  0.000195
4968  0.000199  0.000187
4969  0.000199  0.000183
4970  0.000199  0.000182
4971  0.000199  0.000178
4972  0.000199  0.000177
4973  0.000199  0.000175
4974  0.000199  0.000175
4975  0.000199  0.000175
4976  0.000199  0.000174
4977  0.000198  0.000174
4978  0.000198  0.000174
4979  0.000198  0.000174
4980  0.000198  0.000174
4981  0.000198  0.000174
4982  0.000198  0.000174
4983  0.000198  0.000174
4984  0.000202  0.000235
4985  0.000202  0.000235
4986  0.000202  0.000235
4987  0.000202  0.000235
4988  0.000202  0.000236
4989  0.000202  0.000239
4990  0.000202  0.000235
4991  0.000202  0.000235
4992  0.000202  0.000231
4993  0.000202  0.000231
4994  0.000202  0.000221
4995  0.000201  0.000211
4996  0.000201  0.000210

[4997 rows x 9 columns]

In [68]:
np.savetxt('datatrans2.csv',xsoft, delimiter=',', fmt='%f'
 ,header="R_TEMP,R_DEPTH,R_SALINITY,R_SIGMA,R_SVA,R_DYNHT,R_PRES,R_O2,R_O2Sat")